version: '3.9'

networks:
  reverse-proxy:
    external: true

services:
  box:
    image: archivebox/archivebox:latest
    #command: server --quick-init 0.0.0.0:8000
    ports:
      - 8888:8000
    networks:
      - reverse-proxy
    environment:
      - PUID=99
      - PGID=100
      - TZ=Central/Chicago
      - USE_COLOR=True
      - SHOW_PROGRESS=False
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - /mnt/user/docker/volumes/archivebox/data:/data
      - /mnt/user/docker/volumes/archivebox/cron:/var/spool/cron/crontabs
  scheduler:
    image: archivebox/archivebox:latest
    command: schedule --foreground --update --every=day # archivebox schedule --every=day --depth=1 'https://news.ycombinator.com'
    environment:
      - PUID=99
      - PGID=100
      - TZ=Central/Chicago
      - TIMEOUT=120
    volumes:
      - /mnt/user/docker/volumes/archivebox/data:/data
      - /mnt/user/docker/volumes/archivebox/cron:/var/spool/cron/crontabs
